### ISSUE TITLE
"Failed to parse thread information" when joining after kick

### ISSUE THREAD

**Issue by dequis** [bitlbee/bitlbee-facebook#102]
Cross posting https://github.com/dequis/purple-facebook/issues/244

**Comment by dgw** [comment]
Is this probably why my Facebook account keeps quitting right after znc tries to join the channels? It started pretty recently, like just this weekend, on my system.

**Comment by dequis** [comment]
You'd see that error message if it's this.

**Comment by dgw** [comment]
Sure looks like this. Is there any known workaround?

````
14:13 @dgw ac FB on
14:13 @root facebook - Logging in: Fetching contacts
14:13 @root facebook - Logging in: Connecting
14:13 @root facebook - Logging in: Logged in
14:13 @root facebook - Error: Failed to parse thread information
14:13 @root facebook - Signing off..
14:13 @root facebook - Reconnecting in 5 seconds..
````

**Comment by dequis** [comment]
If it's the exact same thing, check in the website what rooms you've been kicked from, and do "channel #whatever del" to stop joining them. If that doesn't help, get me a debug log.

**Comment by dgw** [comment]
I couldn't figure out from comparing the lists in BitlBee and FB Messenger on my phone, but going the nuclear route and deleting all of the Facebook channels let me connect the account again. Added back the group chats I still use, so it should be easier to debug if it happens again. Thanks!

**Comment by dequis** [comment]
2707fa7895f33f3886616169073fc8b5fabfdd02 fixes this
