### ISSUE TITLE
Login error: User must verify their account on www.facebook.com (405)

### ISSUE THREAD

**Issue by iamcobolt** [bitlbee/bitlbee-facebook#105]
Hi, error:
```
<user> account add facebook <Account> <App Password>
<root> Account successfully added with tag facebook
<user> acc facebook on
<root> facebook - Logging in: Authenticating
<root> facebook - Login error: User must verify their account on www.facebook.com (405)
<root> facebook - Logging in: Signing off..
<root> facebook - Logging in: Reconnecting in 5 seconds..
<user> acc facebook off

```
Using bitlbee-purple on linux.
When connection is attempted facebook account is locked and change password is forced.

Cheers!

**Comment by dequis** [comment]
This is just facebook noticing a connection from an unusual location.

If you're still stuck with that after unlocking the account, log in to the website from the bitlbee server's IP. One way to do that, if you have ssh access to that server:

```
ssh -D localhost:1234 your.server.address.here
```


and then configure your browser to use a socks5 proxy at localhost:1234

**Comment by iamcobolt** [comment]
Thanks,

I had tried this before but upon trying it again it seems to have worked!

**Comment by dequis** [comment]
Yay

**Comment by lrvick** [comment]
Tried the socks proxy method 3x with no luck :(

**Comment by dequis** [comment]
@iamcobolt what service provider do you use for your bitlbee server?

**Comment by iamcobolt** [comment]
I'm using a OVZ VPS, benefits to not using a service provider. host is https://www.k9vps.com/

**Comment by hasmukh2** [comment]
Pls solve login eror 405

**Comment by shymega** [comment]
@hasmukh2 Please provide more information. What versions of bitlbee-facebook, Bitlbee are you using? Do you use 2 factor auth on FB? Bugs can't be fixed with scarce information 🙂

**Comment by stevesbrain** [comment]
@hasmukh2 Additionally, you should open your own ticket. Replying to an old closed ticket will not help! :)

**Comment by garciaErick** [comment]
how do I find out my server address?

**Comment by mikroskeem** [comment]
Errmm... try this: `dig +short myip.opendns.com @resolver1.opendns.com` ?
