### ISSUE TITLE
 possibly undefined macros?

### ISSUE THREAD

**Issue by ryanknutson** [bitlbee/bitlbee-facebook#106]
Running  ./autogen.sh gives me this error. Any way to fix? I'm running it on my Raspberry Pi.

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -Im4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:32: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:33: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by dequis** [comment]
Install libtool.

**Comment by ryanknutson** [comment]
I actually just did that and was going to close but, you beat me to it by a few seconds!
