### ISSUE TITLE
Cannot send or recieve

### ISSUE THREAD

**Issue by ryanknutson** [bitlbee/bitlbee-facebook#109]
So I have Bitlbee and Bitlbee-facebook installed right (I think), and I can see my friends in the list. However, when I try to send them a message, it doesn't get through, and I can't receive any messages.

**Comment by dequis** [comment]
Please get a debug log https://wiki.bitlbee.org/Debugging

It will be full of private stuff (access tokens, friend lists, etc) so don't post it publicly, instead mail it to `dx@dxzone.com.ar`.

**Comment by dequis** [comment]
Poke?

**Comment by ryanknutson** [comment]
Hey I'm sorry, I fixed the issue and forgot to close it. It was just a permission error.

**Comment by dequis** [comment]
Permission error? I don't see how a permission error could result in this. Do you remember more details / got logs saved of when it happened?

**Comment by ryanknutson** [comment]
No I don't sorry. My disk crashed and it was permissions that had messed it up I'm pretty sure.
