### ISSUE TITLE
Nickname encoding issues

### ISSUE THREAD

**Issue by realies** [bitlbee/bitlbee-facebook#110]
I have a few friends that have names using Cyrillic symbols. This results in an unexpected behaviour that can be seen on the screenshot. Any suggestions to where to be looking at for this?

Prioritising custom usernames over the normal facebook user name would be a plus.

<img width="113" alt="capture" src="https://cloud.githubusercontent.com/assets/5107843/19766323/1d943392-9c45-11e6-86d2-5f10cf2120ac.PNG">

**Comment by dequis** [comment]
How about `help set utf8_nicks` in &bitlbee?

**Comment by realies** [comment]
That resolves it. Any reason for utf8_nicks to default to false?

**Comment by dequis** [comment]
That's explained in `help set utf8_nicks` too:

> Officially, IRC nicknames are restricted to ASCII. Recently some clients and servers started supporting Unicode nicknames though. To enable UTF-8 nickname support (contacts only) in BitlBee, enable this setting.
>
> To avoid confusing old clients, this setting is disabled by default. Be careful when you try it, and be prepared to be locked out of your BitlBee in case your client interacts poorly with UTF-8 nicknames.

Anyway glad to hear this is solved, closing.
