### ISSUE TITLE
Upload to Debian?

### ISSUE THREAD

**Issue by spwhitton** [bitlbee/bitlbee-facebook#111]
It would be nice if you could install bitlbee-facebook from the official Debian and Ubuntu repositories.

I maintain several Debian packages so I could help with this.  @jgeboski, are you interested in working towards this?

The first issue is that the version of bitlbee in Debian might be too old.  Not sure.

**Comment by liskin** [comment]
It's not too old. I've been using bitlbee-facebook on Debian testing by just doing `dpkg-buildpackage` in this repo for ages.

**Comment by dequis** [comment]
It seems I never replied to this one but I talked to spwhitton once on irc and, basically: Yeah, sure.

**Comment by spwhitton** [comment]
It just hit Debian sid.

**Comment by dequis** [comment]
Oh btw, any packaging changes we should integrate back?

**Comment by spwhitton** [comment]
On Mon, Mar 20, 2017 at 12:09:08PM -0700, dx wrote:
> Oh btw, any packaging changes we should integrate back?

That's up to you!  I changed a most files in debian/.

-- 
Sean Whitton
