### ISSUE TITLE
FB API "Secret"

### ISSUE THREAD

**Issue by kousu** [bitlbee/bitlbee-facebook#113]
When facebook figures out that [374e60f8b9bb6b8cbb30f78030438895](https://github.com/bitlbee/bitlbee-facebook/blob/ece0715947de3e11c5a726131dcd91900e986f98/facebook/facebook-api.h#L82) is here in the public it will ban bitlbee. The way they want this to work requires bitlbee to keep the [app ID](https://github.com/bitlbee/bitlbee-facebook/blob/ece0715947de3e11c5a726131dcd91900e986f98/facebook/facebook-api.h#L75) and [secret](https://github.com/bitlbee/bitlbee-facebook/blob/ece0715947de3e11c5a726131dcd91900e986f98/facebook/facebook-api.h#L82) in a config file that the user has to fill in after registering as an app developer and [registering for an app](https://developers.facebook.com/apps/async/create/platform-setup/dialog/) on facebook. I agree that it's a lot simpler to just do it this way but it can't last :(

**Comment by dequis** [comment]
This is the secret used by facebook's own mobile apps. User created applications can't work, since they don't have access to many undocumented endpoints they use and the whole 1.0 api.

There are many, many ways in which facebook could block this if they decide they don't like us, and we just have to accept the risk and fix it if it happens.

**Comment by kousu** [comment]
For future reference, if it *were* changed it would completely break bitlbee-facebook. The [changelog](https://developers.facebook.com/docs/apps/changelog#v2_0) no longer contains this explanation, but Facebook's API only returns data about users who have also authorized installed the requesting app e.g. [the developer console will only list your friends who have also tried the developer console](https://developers.facebook.com/tools/explorer?method=GET&path=me%2Ffriends&version=v2.8)

It seems that this particular app key is has been surreptitiously added to every account,  the "facebook itself" key, because all my contacts, including those who have never installed orca, show up when I hit either https://graph.facebook.com/graphql (as facebook-bitlbee does) or https://graph.facebook.com/v2.8/me/friends with it.
