### ISSUE TITLE
Message requests in control channel, and can't be moved to privmsg

### ISSUE THREAD

**Issue by jashank** [bitlbee/bitlbee-facebook#115]
When interacting with people in "message requests" (i.e., chats with people who aren't one's friends), all messages end up in the control channel. It's not consequently possible to move the chat to a privmsg (or if it is I can't easily see how).

**Comment by dequis** [comment]
See `help set handle_unknown`, the default value is add_channel but you may set it to add_private.

You can also reply to them through private messages and bitlbee will remember this for the duration of the session.

**Comment by AdrianKoshka** [comment]
Thanks :)

**Comment by jashank** [comment]
Whoops; I should RTFM more carefully. Thanks for that, sorry for the noise.
