### ISSUE TITLE
Strangers (non-friends) are removed every time

### ISSUE THREAD

**Issue by michelwilson** [bitlbee/bitlbee-facebook#116]
When messaging with strangers/non-friends, these users are removed very quickly. If I haven't sent a message in a few minutes, the user is deleted. The only way to send a message is to use another client (i.e., the web version). This message then appears in bitlbee, and I can resume chatting in bitlbee. It would be nice if there was a way to keep these non-friends as buddies in the contact list somehow.

**Comment by dequis** [comment]
#95, #104

**Comment by michelwilson** [comment]
This is not about group chats, I meant one-on-one chats! I.e., a chat with a user that is not a Facebook friend.

**Comment by dequis** [comment]
Yeah, didn't close it for that reason. Probably the same issue though.

**Comment by dequis** [comment]
82e6bcf0e6f22eeca7eda7ea95aaf8378df6ddef fixes this, please test.

**Comment by michelwilson** [comment]
That change seems to make a big improvement. As long as I stay connected I seem to be able to keep chatting with a 'stranger'. After a reconnect though, I still get no such nick/channel. This is of course not unexpected, as it is not possible to add a stranger to the buddy list. This is probably something that requires a separate issue? Or will this never be supported?

**Comment by dequis** [comment]
I guess you could do `add -tmp facebook <user id> <nickname>`
