### ISSUE TITLE
Don't show as online all the time

### ISSUE THREAD

**Issue by Travolter** [bitlbee/bitlbee-facebook#117]
I use bitlbee on a vps in screen, so I am always connected. Because of this my status is always online, even when I am away.

Would it be possible to create an option to not be shown as online when I am not actively in a conversation?

**Comment by varazir** [comment]
I have the option in irssi to say away status when I disconnect the screen and bitlbee recognize that and set my accounts to away.

**Comment by dequis** [comment]
Yeah, that.

If your irc client is setting /away and the plugin doesn't catch it that's an issue.
