### ISSUE TITLE
"Messenger account" login

### ISSUE THREAD

**Issue by TLATER** [bitlbee/bitlbee-facebook#118]
The Facebook messenger app supports messenger-only accounts.

These do not have a password, instead authentication seem to be handled through a code sent through SMS.

Use of these accounts through this plugin is completely undocumented, if at all possible. So... Is it possible?

**Comment by dequis** [comment]
See also https://github.com/dequis/purple-facebook/issues/237

**Comment by dequis** [comment]
https://github.com/dequis/purple-facebook/issues/237#issuecomment-285926659

tl;dr no reasonable way to implement this
