### ISSUE TITLE
Group chat state (topic, members) not updating after join

### ISSUE THREAD

**Issue by auscompgeek** [bitlbee/bitlbee-facebook#119]
Changes to the group chat name, and members joining and leaving/being kicked (including self!), are not reflected in BitlBee after the user joins the channel.

**Comment by dequis** [comment]
Welp. This was certainly implemented at some point. I'll have a look at it this weekend.

**Comment by auscompgeek** [comment]
Yeah, I definitely remember it working a few months ago. It stopped working sometime in December, from what I can tell from my logs.

**Comment by dgw** [comment]
Huh, it did stop working. I didn't notice until today, when one of my chats' names changed, but to see the updated title in BitlBee I had to part/join the channel.

**Comment by dequis** [comment]
a77eb8feabe9ca8ddebcafc81c2fef981387d3da in the development branch should fix this, please test.

**Comment by dequis** [comment]
This is merged to master now
