### ISSUE TITLE
Always open new conversations in own window

### ISSUE THREAD

**Issue by tiagoboldt** [bitlbee/bitlbee-facebook#123]
Whenever someone new speaks to me, I get the message in the facebook channel window. If I had the user to my bitlbee contacts and open a private chat I then get the message in that separate window. 

I would like to have this behavior by default. Whenever someone spoke to me, it would go directly to  it's own window. 

I've search and didn't manage to find any documentation on this, so I believe this hasn't been implemented yet. If this is not a better behavior for everyone, than maybe it could be a configuration for the connection. 

What do you guys think?

**Comment by dequis** [comment]
Is this about people who are not in your contact list? `help set handle_unknown` in &bitlbee

**Comment by tiagoboldt** [comment]
I guess that would be it. Mine was set to `add_channel`, hence everything was being sent to the channel. I think `add_private` would be the expectable behavior from anyone coming from facebook. So let me change my suggestion to either having `add_private` as default, or explicitly refer to that option in the wiki page that documents the plugin (https://wiki.bitlbee.org/HowtoFacebookMQTT).

Please close the issue if you don't agree. 
Thanks

**Comment by dequis** [comment]
Well, it's not really specific to bitlbee-facebook at all. It works like that for historical reasons, and for some use cases it's desirable to not create query windows, so it's not something that can be changed lightly.

**Comment by tiagoboldt** [comment]
Totally agree, hence suggesting adding the description of the `handle_unknown` configuration in the plugin's page instead of changing any default behavior. Up to you! :)

**Comment by dequis** [comment]
This will do https://wiki.bitlbee.org/FAQ#Why_do_some_people_talk_to_me_through_.26bitlbee.3F
