### ISSUE TITLE
Null value for $.viewer.message_threads.sync_sequence_id

### ISSUE THREAD

**Issue by jashank** [bitlbee/bitlbee-facebook#130]
On sign-in for an already logged-in account. From the log, after a ThreadListQuery:

```
[INFO] facebook:   {"viewer":{"message_threads":{"count":null,"mute_until":0,"nodes":[],"page_info":null,"sync_sequence_id":null,"unread_count":null,"unseen_count":null}}}
[INFO] facebook: Parsing JSON: {"viewer":{"message_threads":{"count":null,"mute_until":0,"nodes":[],"page_info":null,"sync_sequence_id":null,"unread_count":null,"unseen_count":null}}}
[ERROR] facebook: Null value for $.viewer.message_threads.sync_sequence_id
```

**Comment by jashank** [comment]
... and, better, it's transient, and I accidentally nuked that logfile. Damn.

**Comment by dequis** [comment]
Yeah this one is always just a temporary server issue

**Comment by ldionmarcil** [comment]
I'm randomly getting this right now, it's quite irritating.

**Comment by TheTincho** [comment]
I am getting this all the time, can't login any more:
```
[04:23:54] <root> facebook - Logging in: Connecting
[04:23:55] <root> facebook - Login error: Null value for $.viewer.message_threads.sync_sequence_id
```

**Comment by alexolog** [comment]
Same here, on Pidgin.

**Comment by danmdm** [comment]
Same here, on Pidgin too:
Null value for $.viewer.message_threads.sync_sequence_id

**Comment by aoe1** [comment]
Got it just now, basically bitlbee-facebook stopped mid-conversation

**Comment by jcengelsen** [comment]
Got this permanently today. 

**Null value for $.viewer.message_threads.sync_sequence_id**

**Comment by anecznik** [comment]
I have the same problem. I use ubuntu, my sister use windows and don't have any problem.

**Comment by gejr** [comment]
Add my name to the list of people having this issue today.

**Comment by dequis** [comment]
Go to #138
