### ISSUE TITLE
"Failed to parse thread information" after 1.1.0 update

### ISSUE THREAD

**Issue by markrawls** [bitlbee/bitlbee-facebook#139]
Likely related to [138](https://github.com/bitlbee/bitlbee-facebook/issues/138) and the newest update, a previously functioning groupchat now returns the titular error. Packages updated, Inetd restarted, server rebooted, all the usual debugging steps. This is also what showed up promptly before the old API retiring hit my account.

Attempting to manually delete groupchat from config and rejoin manually with "chat add facebook 1111111 #channel-name" I simply get "Could not add chatroom."

**Comment by dequis** [comment]
Please check for errors in &bitlbee, the kick in the room is meaningless, just a reference to the other error.

>Attempting to manually delete groupchat from config and rejoin manually with "chat add facebook 1111111 #channel-name" I simply get "Could not add chatroom."

That error means #channel-name already exists. Use a different name, remove the other one, or just change its room setting. See `help channel`

**Comment by markrawls** [comment]
My apologies. Removed the channel and readded, tried to join, and received the error in &bitlbee

`facebook - Error: Failed to parse thread information`
`facebook - Signing off..`

**Comment by dequis** [comment]
2f17542c7a866f1963b0b51b01736652d53dd70d should help

**Comment by markrawls** [comment]
Yep, that did it! Thank you!

**Comment by dequis** [comment]
Let's keep this one open for visibility

**Comment by dequis** [comment]
Waited a bit to release it but there it is https://github.com/bitlbee/bitlbee-facebook/releases/tag/v1.1.1
