### ISSUE TITLE
Login failed due to SSL connection error

### ISSUE THREAD

**Issue by psukys** [bitlbee/bitlbee-facebook#143]
Hello,
bitlbee-facebook fails to login and the following error occurs:

     Login error: Unable to connect to b-api.facebook.com: SSL Connection Failed

Tried running with environment variable `BITLBEE_DEBUG_FACEBOOK=1`, yet didn't get any output at all

**Comment by dequis** [comment]
Use BITLBEE_DEBUG=1 instead. See also https://wiki.bitlbee.org/Debugging

**Comment by psukys** [comment]
Alright, `BITLBEE_DEBUG=1` seemed to work. The problem was with dns lookup - out of memory

```
DEBUG socket: invalid state: 3 (should be: 2)DEBUG http: Request 0x7fa4e7436a50 performed without success.
DEBUG connection: Connection error on 0x7fa4e742a2d0 (reason: 0 description: Unable to connect to b-api.facebook.com: SSL Connection Failed)
DEBUG dns: Could not create child process for DNS: Cannot allocate memory
```
seems that it needed quite some amount of memory at that time (200-300MB?). Shutting down other processes and the problem resolved

**Comment by dequis** [comment]
What operating system / architecture?

Also, that's libpurple

**Comment by psukys** [comment]
Ubuntu x64 16.04

**Comment by psukys** [comment]
Ubuntu x64 16.04
