### ISSUE TITLE
Media pasted into messenger.com doesn't appear in BitlBee

### ISSUE THREAD

**Issue by dgw** [bitlbee/bitlbee-facebook#146]
Apparently it's possible to paste images (at least) into the `messenger.com` UI and send them that way. I didn't know it was possible until a friend sent an image using that method to a mutual group chat. It's remarkable because images sent this way do not appear in BitlBee.

I'm guessing this is another obnoxiously-long attachment URL situation, like #97…

**Comment by dequis** [comment]
See #147, tl;dr reopen if it still happens

**Comment by dgw** [comment]
I think this is also a duplicate of #73, actually. Found that error message in logs from the day before I filed this, so apparently I'm just blind and should be banned from filing issues without talking to @dequis on IRC first.
