### ISSUE TITLE
Recent problems with photos not coming through to BitlBee chats

### ISSUE THREAD

**Issue by dgw** [bitlbee/bitlbee-facebook#147]
Using `bitlbee-facebook` 1.1.1, it seems that photos shared in group chats using methods that used to appear in BitlBee (as links, of course) might no longer work, perhaps due to changes in how Facebook sends them along.

For example, photos sent using Messenger's camera might not appear any more. (That's what got me to look into this.) In testing, I was able to send a photo from Messenger Lite using a third-party camera (Open Camera) and it appeared in BitlBee—and sharing an image from Facebook to Messenger Lite worked as well. It might be only certain photos that fail, or certain chats, I'm not sure.

**Comment by dequis** [comment]
What's the difference with #146?

I can't reproduce either of these. A debug log would help. What facebook messenger version?

**Comment by dequis** [comment]
Sup

**Comment by dgw** [comment]
Let's just close this. I haven't been able to repro for a while. Will reopen with more info if I can get it.

**Comment by dequis** [comment]
Same thing with #146 then?

**Comment by dgw** [comment]
Close it if you like. Either way, I'll be back with more info if reproduced.

**Comment by dgw** [comment]
Typical… As soon as I close this for lack of repro, it repros. I'm bugging the other party for more info, and will try to set up a debug chat so we don't spam everyone else in our groups. Assuming I can reliably reproduce this and figure out how to get debug logs, you'll have them as soon as they're generated.

**Comment by dgw** [comment]
Discussed with @dx on IRC and determined while getting debugging going that this is actually a duplicate of #73. I missed the error message in among all the join/part spam in my root channel.
