### ISSUE TITLE
Could contacts stay &bitlbee?

### ISSUE THREAD

**Issue by Taipsi** [bitlbee/bitlbee-facebook#150]
Hi!

Would it be possible to change behavior (or make it configurable) so that contacts would stay always &bitlbee instead of joins and quits and present their online status with +v? For example telegram/libpurple I'm using works this way and it makes sending messages to offline contacts easier. This would also reduce amount of activity which of course can be achieved using /ignore.

Just my thought to make this great software even better :)

**Comment by dequis** [comment]
`help set show_users`

**Comment by fuzzy76** [comment]
Came here for this. It's [missing in the documentation](https://wiki.bitlbee.org/HowtoFacebookMQTT).
