### ISSUE TITLE
Login error: Failed to read thrift: facebook-api.c:1815 fb_api_cb_publish_pt: assertion 'FALSE' failed

### ISSUE THREAD

**Issue by Hello71** [bitlbee/bitlbee-facebook#151]
`type = FB_THRIFT_TYPE_I64`, dunno what's in it.

**Comment by NPKJI** [comment]
I'm getting the same issue.  Sounds like it's related to this: 

https://github.com/dequis/purple-facebook/issues/357

**Comment by dequis** [comment]
Yes, duplicate of https://github.com/dequis/purple-facebook/issues/357

**Comment by dequis** [comment]
...nevermind, different repo

**Comment by dequis** [comment]
Fix https://github.com/bitlbee/bitlbee-facebook/commit/e460983b98aa29c222b3990c41c16355d8fe78a1

**Comment by dequis** [comment]
Release https://github.com/bitlbee/bitlbee-facebook/releases/tag/v1.1.2

**Comment by AhmedSuhel** [comment]
Pils help

**Comment by Hello71** [comment]
i think this was fixed? not sure, i don't use bitlbee-facebook anymore
