### ISSUE TITLE
jgeboski's Package repository removed?

### ISSUE THREAD

**Issue by malinkb** [bitlbee/bitlbee-facebook#154]
The jgeboski repo seems to be removed

http://download.opensuse.org/repositories/home:/jgeboski/

When will @dequis repo be ready?

**Comment by dequis** [comment]
ffs

Consider it downtime

**Comment by dequis** [comment]
https://news.opensuse.org/2017/10/04/planned-downtime-to-affect-opensuse-services/

They seem to be busy starting all the servers again. Sounds like it will take a few hours.

**Comment by malinkb** [comment]
Okey. I was too fast to assume the repo was removed. I could find a lot of repos under http://download.opensuse.org/repositories/home:/  but I couldn't find jgeboski's which led me to belive it was removed.

**Comment by dequis** [comment]
It came back a while ago, closing
