### ISSUE TITLE
group chats not showing up

### ISSUE THREAD

**Issue by gregf** [bitlbee/bitlbee-facebook#159]
I have a group chat with 3 people in it. I never get messages for it in my bitlbee session. I have to sign into facebook's website to see them. Not sure how to debug? Let me know if I can provide you some information.

**Comment by dgw** [comment]
bitlbee-facebook doesn't auto-join new group chats by default. It will only show chats you add with `fbchats` then `fbjoin chatID #channel_name` unless you tell &bitlbee `account facebook set group_chat_open all`.

The [plugin wiki page](https://wiki.bitlbee.org/HowtoFacebookMQTT) explains in more detail, but if that doesn't help feel free to continue the discussion here.

**Comment by gregf** [comment]
That sorted it out, sorry I didn't see the wiki before.
