### ISSUE TITLE
Unable to log in since Jan 12

### ISSUE THREAD

**Issue by drvink** [bitlbee/bitlbee-facebook#166]
`bitlbee-facebook` has worked flawlessly for over a year, up until now, where it just stalls at "Logging in: Fetching contacts".  I've tried recreating the account, can log in to Facebook via other methods, and Facebook doesn't think there's anything sketchy about the host from which I was connecting.

With `BITLBEE_DEBUG_FACEBOOK=1` in my environment, I see a request for `fb_api_req_friendly_name=FetchContactsFullQuery` `...more stuff...`, and I never appear to get a response--perhaps something changed in the protocol, or maybe the `bitlbee-facebook` API key has been blocked?

**Comment by stevesbrain** [comment]
Are you using 2FA?

**Comment by dequis** [comment]
Try `git revert cdc41b66`, rebuild and report results.

**Comment by shymega** [comment]
@stevesbrain I know I'm not OP, but I've just had this issue, and I am also using 2FA. 

I've tried @dequis's suggestion, to no avail. It still stalls on 'Fetching contacts'. Occasionally my bitlbee instance times out from Facebook as well. I'm leaning towards the hypothesis that FB have changed something server-side. I note I had a FB Messenger update recently.. it could be that the protocol changed a little. Bah, FB :P

**Comment by drvink** [comment]
I am using 2FA, and reverting that commit and rebuilding didn't work for me either.

**Comment by shymega** [comment]
I should also add, on the FB Messenger app, including beta, I have noticed personally a lot more instability, even on non-beta.. not especially sure if FB are mucking around or something. *shrugs*

**Comment by stevesbrain** [comment]
@drvink Tried using an app password instead of your regular then? Bypasses 2FA. Having said that, I've had issues (namely with https://github.com/rg3/youtube-dl) where even with an app password, it won't authenticate. I have to turn off 2FA, auth, then turn it back on.

**Comment by dequis** [comment]
This is post-auth, if you get to fetching the contact list you already have a working access token.

**Comment by shymega** [comment]
Interesting, its now working for me. I haven't changed anything.. just a heads up. :confused:

**Comment by dequis** [comment]
The debug log I got didn't clarify a lot - it just showed the sent http request, no response, and I assume it dies with a timeout.

I'm going to guess this is ipv6 related, so try adding an entry to /etc/hosts with this to force it to use ipv4:

    31.13.94.19 graph.facebook.com

Or whatever ipv4 resolves for you for that domain. Make a note to remove this entry at some point in the future, no guarantee it will stay with that address forever.

There's also the fact that purple-facebook users (which are way more) never had this issue. Residential ISPs provide ipv6 less often and if they do they probably care more about not breaking routes to facebook.

**Comment by drvink** [comment]
Wow, good guess. Indeed, it was IPv6--disabling the v6 interface on the machine from which I run bitlbee made it work immediately. I guess this can be closed!
