### ISSUE TITLE
Handling long messages inserts an extra space

### ISSUE THREAD

**Issue by realies** [bitlbee/bitlbee-facebook#169]
When using `bitlbee-facebook` with the option to concatenate long messages when they're received between a certain time interval, `bitlbee-facebook` concatenates the messages by inserting an additional space character after each concatenated message. This, for example, breaks long URLs. Would it possible to concatenate without a space between messages?

**Comment by dequis** [comment]
That's not bitlbee-facebook, that's bitlbee's `paste_buffer`, closing because this doesn't belong here.

Also, it's not a space, it's a newline, because the feature is about sending multiple lines as a single message. Not sure what to do there.
