### ISSUE TITLE
Cannot activate facebook account in bitlbee

### ISSUE THREAD

**Issue by thorgrin** [bitlbee/bitlbee-facebook#192]
Starting yesterday, I'm getting this error:
```
account facebook on
10:53:38 <@root> Unknown protocol `hal_VOID__POINTER_BOOLEAN'
```
I'm using packages on Ubuntu 18.04:
```
Package: bitlbee-plugin-facebook
Version: 1.1.2-1

Package: bitlbee
Version: 3.5.1-1build1
```

i've also tried building the 1.2.0 version from git, but the error stays the same. What can I do to fix this?

**Comment by dequis** [comment]
Does the `plugins` command in &bitlbee say you have the correct version?

**Comment by thorgrin** [comment]
Yes, it does. I checked the bitlbee confiuration xml file and the plugin protocol was set to the hal_VOID__POINTER_BOOLEAN. So there was definitely some kind of memory corruption, but that would be hard to find. After changing that back to `facebook`, I get the usual 405 error. I guess that this can be closed, then.
