### ISSUE TITLE
"Error: The action attempted has been deemed abusive or is otherwise disallowed" every `sync_interval` minutes

### ISSUE THREAD

**Issue by zer0def** [bitlbee/bitlbee-facebook#194]
As of about 2 hours ago, users may have started to experience the error from the title, quick tinkering with available options suggests it happens every `sync_interval` minutes, so setting it to a high value (say, `43200` for a month) is a temporary workaround.

**Comment by Perdu** [comment]
Where do you configure `sync_interval`? Thanks

**Comment by ekianjo** [comment]
same question as @Perdu , @zer0def  - no idea where you can set this up, Appreciate if you can point us to the right place to modify this.

**Comment by zer0def** [comment]
Assuming your Bitlbee IM account ID is `facebook` (or whatever numeric ID you have for it), that'd be `account facebook set sync_interval <int>`.

**Comment by tripkin** [comment]
I just started getting that error message with my facebook account. I followed the instructions setting the sync interval to 43200, but as soon as I log in facebook disconnects me citing the error: 
"facebook - Login error: The action attempted has been deemed abusive or is otherwise disallowed"

An hour ago it would let me log in and then disconnect me after a few minutes, now it will not even let me log in. <sigh>

I blame Facebook, of course...

**Comment by zer0def** [comment]
I guess daddy Zucc got upset with you abusing his machines, perhaps you guys need a break from each other for a couple of hours? Just be sure to check up on the site about how badly he might've gotten offended.

**Comment by tripkin** [comment]
Yeah, maybe so. Nothing on the site that I can find that is related to this, however. Zucc is being quiet about his rage...

**Comment by tripkin** [comment]
Yup, just had to wait. Thank you for the solution!

**Comment by tripkin** [comment]
And... No. I can connect just fine with Caprine, but this plugin gets rejected every time I try to connect with it. Unfortunately, I do not know how to actually diagnose the problem, but my account is fine and the plugin is using an app password generated at Facebook.

Any ideas on what else i can do to help troubleshoot this?

**Comment by Epistam** [comment]
Hello ! 
I have the same problem, `account facebook set sync_interval 43200` didn't seem to fix my problem, even after waiting a whole night without trying to connect.

I am using Bitlbee-facebook + Weechat. Any ideas as to what might be the problem here ? 

Thank you in advance !

**Comment by ekianjo** [comment]
> Assuming your Bitlbee IM account ID is `facebook` (or whatever numeric ID you have for it), that'd be `account facebook set sync_interval <int>`. Be sure to `save` afterward.

How did you find this out? this is not even documented on bitlbee...

**Comment by ekianjo** [comment]
@Epistam indeed this does not fix anything either on my side

**Comment by kimmov-kipe** [comment]
My Bitlbee also didn't get the connection up again with the sync_interval of 43200. Instead I was immediately thrown out.
However, with the sync_interval set to 1440 seems to work, at least for now. Seems to keep connecting for more than just the day, too.

**Comment by tripkin** [comment]
Awesome! Thank you. That little tweak has me working for now. Let's hope it continues to work...

**Comment by Epistam** [comment]
@kimmov-kipe That seems to do the trick for me too. Thank you !

**Comment by dequis** [comment]
1.2.2 forces sync_interval to be more than 5 minutes, defaults to 1440.
