### ISSUE TITLE
Support having only a messenger.com account

### ISSUE THREAD

**Issue by mslot** [bitlbee/bitlbee-facebook#206]
I only have an account bound to my phone number, on messenger.com. I have installed bitlbee and bitlbee-facebook. When i run

> account add facebook [my number] {my password]
> account facebook on

I get an error saying 

> 08:14        root| facebook - Logging in: Authenticating
> 08:14        root| facebook - Login error: Invalid username or password (401)
> 08:14        root| facebook - Logging in: Signing off..

I could indicate that users on messenger.com uses another protocol?

This is my info
 >08:11        root| [13:16:27] Running BitlBee 3.6-1.1ubuntu1
 >08:13        root| Plugin                          Version
 >08:13        root| facebook                        1.2.0
 >08:13        root|
 >08:13        root| Enabled Protocols: facebook, hipchat, identica, jabber, twitter

**Comment by dequis** [comment]
Last time I checked, this was not possible: https://github.com/dequis/purple-facebook/issues/237
