### ISSUE TITLE
two-factor authentication forced on 15 September

### ISSUE THREAD

**Issue by dchmelik** [bitlbee/bitlbee-facebook#215]
FB is forcing two-factor authentication on some by 15 Sep: SMS, 'app', or physical key (see below).

> Your account requires stronger security from Facebook Protect
>
>Hi \<name\>,
> 
>We're upgrading protection for Facebook accounts like yours and need your help to enable a required security programme by 15 September. It's called Facebook Protect and it uses advanced security measures to help defend your account against potential vulnerabilities.
>	Turn on Facebook Protect for your account by 15 September. After that, you may not be able to access your account until you've done so.
>  To enable Facebook Protect:
>    1. Log in to your account on Facebook.
>    2. Go into security settings and look for the Facebook Protect option.
>    3. Follow the steps to enable the programme for your account.
>  For security reasons, we have not included direct links to Facebook Protect in this email.
>  \<name\>
>  Requires Facebook Protect
>
>Thanks,
>The Facebook Security Team

**Comment by usvi** [comment]
I made an experimental patch to support 2FA directly: https://github.com/usvi/bitlbee-facebook/commit/31b56ec07d8b1682a15e1dde114810140dddcb4e 

Any feedback is appreciated while waiting for bitlbee-facebook maintainership to resolve itself.

**Comment by Thaodan** [comment]
> I made an experimental patch to support 2FA directly: [usvi@31b56ec](https://github.com/usvi/bitlbee-facebook/commit/31b56ec07d8b1682a15e1dde114810140dddcb4e)
> 
> Any feedback is appreciated while waiting for bitlbee-facebook maintainership to resolve itself.

That looks interesting, please put it to a separate instead of commit to master, doing so makes it easier to adapt.

**Comment by usvi** [comment]
> > I made an experimental patch to support 2FA directly: [usvi@31b56ec](https://github.com/usvi/bitlbee-facebook/commit/31b56ec07d8b1682a15e1dde114810140dddcb4e)
> > Any feedback is appreciated while waiting for bitlbee-facebook maintainership to resolve itself.
> 
> That looks interesting, please put it to a separate instead of commit to master, doing so makes it easier to adapt.

Alright, I will make it into a branch. I'll ping people back when I'm done (might take a day or two).

**Comment by usvi** [comment]
> > I made an experimental patch to support 2FA directly: [usvi@31b56ec](https://github.com/usvi/bitlbee-facebook/commit/31b56ec07d8b1682a15e1dde114810140dddcb4e)
> > Any feedback is appreciated while waiting for bitlbee-facebook maintainership to resolve itself.
> 
> That looks interesting, please put it to a separate instead of commit to master, doing so makes it easier to adapt.

Am I doing in right:

https://github.com/usvi/bitlbee-facebook/tree/automatic-2fa-tokens

**Comment by dchmelik** [comment]
@usvi the patch didn't work for me: I never receive confirmation code.

**Comment by usvi** [comment]
Oh no! @dchmelik : Do you happen to have IRC-style chat or something else such available where we could change ideas and coordinate debugging?

**Comment by dchmelik** [comment]
> Do you happen to have IRC-style chat or something else such available where we could change ideas and coordinate debugging?

I can come to OFTC IRC #bitlbee

**Comment by dchmelik** [comment]
After usvi's help, and uninstalling libpurple-facebook (which resulted in no more FaceBook (FB) in pidgin, which wasn't working with it anyway) I got it working with bitlbee again.
