### ISSUE TITLE
mark_read on reply

### ISSUE THREAD

**Issue by gardar** [bitlbee/bitlbee-facebook#68]
When I've been using bitlbee and go back to a browser or android messenger it looks like all the messages I've exchanged back and forth are unread.

I do not want to turn on mark_read since it will make bitlbee grab all the conversations and I will not be notified on my android messenger.

Would it be possible to send mark_read each time you send a reply in a conversation?

**Comment by dequis** [comment]
This was implemented by #69, do this to enable it:

```
account facebook set mark_read_reply true
```

**Comment by Isgar** [comment]
Could you clarify, does this mark all messages as read, or only in the thread replied to?

**Comment by mhalden** [comment]
It only marks the thread you reply to as read.
