### ISSUE TITLE
Contacts sometimes disappear for a few hours with quit message "Removed"

### ISSUE THREAD

**Issue by spwhitton** [bitlbee/bitlbee-facebook#74]
My contacts sometimes disappear like this:

    12:49 -!- foo [bar@facebook] has quit [Removed]

While they are 'away', their messages appear in &bitlbee:

    14:37 <@foo> spwhitton: blah blah

During this time I can converse with the contact using &bitlbee.  Then a few hours later they come back and I can /msg them again.  How can I debug this?  Thanks.

**Comment by jgeboski** [comment]
Someone else has reported this, and I have yet to be able to recreate it.

**Comment by dequis** [comment]
@spwhitton how many friends do you have?

**Comment by spwhitton** [comment]
On Sat, Mar 26, 2016 at 05:21:12PM -0700, dx wrote:
> @spwhitton how many friends do you have?

Well if you mean Facebook friends .. 640.

-- 
Sean Whitton

**Comment by dequis** [comment]
So maybe it's related to the contact list pagination being broken. It currently fails to fetch results after the first 500 contacts.

I guess that list isn't ordered so sometimes the contacts you want to have are in the first 500 and sometimes they are not.

As a crappy workaround, when you have the contacts you want to have, do this to avoid doing more syncs that may make you lose people:

```
account facebook set sync_interval 99999
```

That number is minutes, minimum 5, default 30.

If you don't have the contacts you want to have, maybe reconnect the account to roll again.

**Comment by dequis** [comment]
Actually, make that 9999 instead of 99999

(Just realized that `99999 * 60 * 1000` doesn't fit in 32 bits)

**Comment by dequis** [comment]
There's a patch in the [development branch](https://github.com/jgeboski/bitlbee-facebook/tree/development) fixing this

**Comment by dequis** [comment]
That commit got merged to master some time ago, closing this.
