### ISSUE TITLE
facebook group chat echos my messages

### ISSUE THREAD

**Issue by malinkb** [bitlbee/bitlbee-facebook#76]
When I send a message or write to the group chat buffer, I get the message in retur. 

Just like if you use echo from a shell.

**Comment by dequis** [comment]
Issue in the other tracker: https://github.com/jgeboski/purple-facebook/issues/226

**Comment by manavortex** [comment]
Hey, 
I think for Facebook the magic is somewhere inside

    ´    for (m = thrd->users, j = 0; (m != NULL) && (j < 3); m = m->next, j++) {
            user = m->data;
            g_string_append(line, (j != 0) ? ", " : "  ");
            g_string_append(line, user->name);
        }´

..?

**Comment by dequis** [comment]
@manavortex That's the code that writes the list of participants in the third column of the 'fbchats' command

**Comment by kimmov-kipe** [comment]
Experienced this today for the first time. Might it be that this only occurs in groupchats started by you yourselves? That's the situation I have here. Other groupchats started by other people (which I only had before today) are not echoing my lines, only these two chats I opened myself today.

**Comment by auscompgeek** [comment]
@kimmov-kipe I'm reproducing this bug in a single group chat I'm in, of which I did not create, so it's not that.

**Comment by anlag** [comment]
I'm experiencing this as well. This behaviour started when I updated to bitlbee 3.4.2. The bitlbee-facebook plugin version is  however the same as before, 1.0.0. I have the issue in all chats that I've tried; I don't believe I created any of them.

Considered that it might be an issue with carrying an old profile from the previous bitlbee version, so I tried creating a clean one and re-adding the Facebook account, but it happens in the same way.

**Comment by dequis** [comment]
@anlag You're probably talking about a different issue. Try rebuilding the plugin.

**Comment by dequis** [comment]
Just pushed 0877cf236761eaefcd61b8fd5722272ffe1f12c5 which "fixes" this by saving the sent message ID, to be handled by the message deduplication code (which was added when the server started sending repeated messages many times). This isn't perfect and will fail with fast moving chats, but better than nothing.
