### ISSUE TITLE
bitlbee-facebook errors seem to make bitlbee segfault

### ISSUE THREAD

**Issue by levu42** [bitlbee/bitlbee-facebook#81]
Earlier today I noticed bitlbee segfaulting every few minutes, so I dig into it and enabled the bitlbee debug log. The last entry in the debug log is always an »[ERROR] facebook: …« (e.g.: Connection timed out).

I tested it with bitlbee-facebook v.1.0.0 and master, together with bitlbee 3.4.1 and 3.4.2.

**Comment by dequis** [comment]
Please get a backtrace, either by running it under gdb or opening a coredump.

What distro?

**Comment by dequis** [comment]
You can also try running it under valgrind. Install valgrind, kill the current bitlbee processes, and run

```
BITLBEE_DEBUG=1 valgrind --log-file=valgrind.log bitlbee -Dnv
```

Valgrind will probably prevent the crash and continue running, but write relevant debug output to valgrind.log. Please post that if it shows anything.

**Comment by levu42** [comment]
The only log entry so far after 10 minutes of running (without using valgrind it crashes right after one or two minutes):

```
Conditional jump or move depends on uninitialised value(s)
   at 0x6DD64E0: inflateReset2 (in /lib/x86_64-linux-gnu/libz.so.1.2.3.4)
   by 0x6DD65D8: inflateInit2_ (in /lib/x86_64-linux-gnu/libz.so.1.2.3.4)
   by 0x8125AD9: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.3200.4)
   by 0x8404B82: g_object_newv (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)
   by 0x8404EC5: g_object_new_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)
   by 0x84051D3: g_object_new (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)
   by 0x7C7060F: fb_util_zlib_inflate (facebook-util.c:374)
   by 0x7C653C2: fb_api_cb_mqtt_publish (facebook-api.c:1667)
   by 0x83FDCA1: g_closure_invoke (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)
   by 0x840ED70: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)
   by 0x8417068: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)
   by 0x8417723: g_signal_emit_by_name (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.3200.4)

```

**Comment by levu42** [comment]
Oh, and the distribution is Ubuntu 12.04.

**Comment by dequis** [comment]
Huh, nothing else? That one looks harmless to me.

FWIW, I wrote this page yesterday https://wiki.bitlbee.org/DebuggingCrashes

**Comment by dequis** [comment]
I'm going to go ahead and assume this is the same thing as #82, given the timing of this report and others.
