### ISSUE TITLE
Unidentified user in group chat

### ISSUE THREAD

**Issue by anlag** [bitlbee/bitlbee-facebook#83]
Running bitlbee version 3.4.1, bitlbee-facebook version 1.0.0, both compiled from source on 64-bit Ubuntu.

I have at least one user in Facebook group chats who isn't identified properly in bitlbee. Instead of a name, I see an underscore followed by nine digits when this person speaks, like so:

`12:31 < _123456789> hi`

Using /names to list chat members doesn't include the person at all, neither with name nor numbers. Opening the chat on messenger.com I can see the person normally, name and all. I tried to probe the user with /whois, and to rename with "rename _123456789 RealName" in &bitlbee, but both inform me there is no such user. The alias would have otherwise been a convenient workaround, to keep track of who is who, should this occur with other users.

I am not friends with the user in question, but there are many others in the same chat that I am also not friends with, and they still show up fine. I'm tentatively assuming it's a privacy setting on this user's part, but since the name is visible on the site, I am hoping there's a way to retrieve it also via the API that bitlbee-facebook uses.

I tried searching for this issue but was unsuccessful, apologies if it's there and I simply missed it. Thanks also for a great plugin, that finally makes the ubiquitous Facebook chat accessible in a sensible and readable format.

**Comment by dequis** [comment]
Does this still happen after reconnecting the account?

If you go to the profile of this contact (facebook.com/123456789), does it look unusually locked down or showing a 404?

>Running bitlbee version 3.4.1, bitlbee-facebook version 1.0.0, both compiled from source on 64-bit Ubuntu.

3.4.1 is old, update to 3.4.2 please.

There are APT repos, http://code.bitlbee.org/debian/README.html and https://jgeboski.github.io/

**Comment by anlag** [comment]
Reconnecting the account (ie "account facebook off", "account facebook on" in &bitlbee) resolved the issue and made the name appear as normal.

The profile of the user looks fine as I check it now also. 

Before the reconnect yesterday, I saw another user appear with numbers only. In both cases, I hadn't been in chats with them before, and in both cases, the reconnect fixed it. This was before updating to 3.4.2, of course it still works after the update.

I will close the issue. Thanks!
