### ISSUE TITLE
Error "No matches for $.viewer.message_threads.sync_sequence_id"

### ISSUE THREAD

**Issue by TheBlusky** [bitlbee/bitlbee-facebook#84]
Hello !
Not sure if this is an issue, but since today, I can't connect properly to facebook.
I have this error :

> <@blusky> account 1 on
> <@root> facebook - Logging in: Fetching contacts
> <@root> facebook - Logging in: Connecting
> [...]
> All my contacts join &bitlbee
> [...]
> <@root> facebook - Login error: No matches for $.viewer.message_threads.sync_sequence_id
> <@root> facebook - Logging in: Signing off..
> -!- Netsplit localhost.localdomain <-> myhost.com quits: [...] my contacts [...]
> <@root> facebook - Logging in: Reconnecting in 900 seconds..

Any idea ?

Edit: Forget about it, it just solved on its own ... Maybe keep it for archiving...

**Comment by burnseyeview** [comment]
I'm also experiencing this. running `account 1 on` will show facebook connecting, a short list of fb users,. then the error.

**Comment by dequis** [comment]
@burnseyeview  Go to #138

**Comment by burnseyeview** [comment]
smashing! thank you, sir
