### ISSUE TITLE
Feature request: Notofications

### ISSUE THREAD

**Issue by varazir** [bitlbee/bitlbee-facebook#87]
Hello, 

If it can be done to make the plugin show all notifications in a channel. 
Example if someone likes something or post or reply to a post.  

Why is that I like to uninstall the facebook app and I use the irssinotification plugin and app on my phone so all highlights get pushed to my phone.

TIA
Daniel

**Comment by dequis** [comment]
Last time i checked, we don't get that in the mqtt stream at all. This plugin implements what the 'messenger' android app implements, not what the 'facebook' app implements. If something changed and this feature is included in the messenger android app, I might reconsider. Otherwise, can't be done.

**Comment by varazir** [comment]
Okay :( if you don't get that info nothing can be done.
Den 5 juni 2016 7:18 em skrev "dx" <notifications@github.com>:
