### ISSUE TITLE
Feature request: Event invites

### ISSUE THREAD

**Issue by varazir** [bitlbee/bitlbee-facebook#88]
Hello (again) 

I would like to have a fbevent command that you can accept invites. 

TIA 
Daniel 

PS sorry for "spamming"  but imo from a support point of view one "ticket" per feature. Yes I work with support DS 

PS2 I really like this plugin so keep the good work up DS2

**Comment by dequis** [comment]
Same thing as the previous ticket:

>Last time i checked, we don't get that in the mqtt stream at all. This plugin implements what the 'messenger' android app implements, not what the 'facebook' app implements. If something changed and this feature is included in the messenger android app, I might reconsider. Otherwise, can't be done.
