### ISSUE TITLE
Apt repos disappeared?

### ISSUE THREAD

**Issue by basepi** [bitlbee/bitlbee-facebook#91]
@jgeboski's repos on downloads.opensuse.org seem to have disappeared. Is this intentional?

**Comment by dequis** [comment]
Huh? Works for me

https://build.opensuse.org/package/repositories/home:jgeboski/bitlbee-facebook
http://download.opensuse.org/repositories/home:/jgeboski/
http://download.opensuse.org/repositories/home:/jgeboski/Debian_8.0/

**Comment by basepi** [comment]
I swear I drilled down through download.opensuse.org and couldn't find the repo. Strange. You're certainly right, the repos are there now.
