### ISSUE TITLE
Any way to get conversation history?

### ISSUE THREAD

**Issue by seb321** [bitlbee/bitlbee-facebook#94]
Hi,
(sorry for my English, it's not my native language)
I can't find anything useful in Internet, so I write here. Is there any way to get chat history?

**Comment by Zopieux** [comment]
Based on the very nature of IRC, there is no builtin feature to go back in time. Think of IRC (thus bitlbee) as an event-based gateway that can only *push* notifications when they arrive, but are then lost [in the nether](https://www.youtube.com/watch?v=qz5i171h_no&t=52s) upon receipt.

Although it's technically feasible, by using some kind of on-demand history (eg. `/lastlog 1 day`), I don't believe bitblee-facebook will ever implement such a mechanism.

**Comment by seb321** [comment]
Thanks for response.
I think built-in function would be great, howewer I'll look on `/lastlog`.
