### ISSUE TITLE
Non-friends in group chats get "Removed"

### ISSUE THREAD

**Issue by dgw** [bitlbee/bitlbee-facebook#95]
bitlbee: 3.4.2
bitlbee-facebook: `609ca2d`

One of my group chats had someone I'm not friends with added to it the other day. A few hours later, that person "left IRC (Removed)", despite still being in the group chat.

Parting and rejoining the channel brought back the "Removed" participant for a while, but soon enough the same thing happened again.

I don't know if this is related to #74, since that had to do with contacts on the BitlBee user's friends list and this is an issue with non-friends, but it's the only other reference I could find to "Removed" in the issues for this plugin.

**Comment by stevesbrain** [comment]
Just chiming in with my $0.02 to say I am affected by this also (not just a solo case for @dgw )

**Comment by dequis** [comment]
82e6bcf0e6f22eeca7eda7ea95aaf8378df6ddef fixes this, please test.
