### ISSUE TITLE
Link attachments sent from Android do not appear in BitlBee

### ISSUE THREAD

**Issue by dgw** [bitlbee/bitlbee-facebook#97]
I shared two links at different times yesterday from Chrome to Messenger group chats on my phone. The comments I added to the links came through in BitlBee as self-messages, but the links themselves are nowhere to be found.

Here are the steps I used:
1. Open a page I want to share in Chrome for Android
2. Use the Share menu and select Messenger
3. When Messenger opens, check the box next to one of my group chats, and add a comment in the box at the top
4. Send the message

Result: Messenger will display the comment and its attached link. BitlBee will display only the comment.

**Comment by dequis** [comment]
The url field from one of those messages is

>"url": "fbrpc://facebook/nativethirdparty?app_id=256002347743983&app_name=Facebook+Messenger+for+Android&class_name=com.facebook.orca.auth.StartScreenActivity&fallback_url0=https%3A%2F%2Fm.facebook.com%2Fapps%2Ffbmessenger_android&market_uri=market%3A%2F%2Fdetails%3Fid%3Dcom.facebook.orca%26referrer%3Dutm_source%253Dapps.facebook.com%2526utm_campaign%253Dfb4a%2526utm_content%253D%25257B%252522app%252522%25253A256002347743983%25252C%252522t%252522%25253A1468764859%25257D&package_name=com.facebook.orca&tap_behavior=app_fallback_web&target_url=http%3A%2F%2Fwww.google.com%2F%3Fgfe_rd%3Dcr%26ei%3DjJKLV4-OEIzX8gfuvLG4Bw&key_hash0=fake_hash&extra_applink_key=al_applink_data&referer_data_key=extras&al_applink_data=%7B%22target_url%22%3A%22http%3A%5C%2F%5C%2Fwww.google.com%5C%2F%3Fgfe_rd%3Dcr%26ei%3DjJKLV4-OEIzX8gfuvLG4Bw%22%2C%22extras%22%3A%7B%22fb_app_id%22%3A256002347743983%7D%2C%22referer_app_link%22%3A%7B%22url%22%3A%22fb-messenger%3A%5C%2F%5C%2F%5C%2F%22%2C%22app_name%22%3A%22Messenger%22%2C%22package%22%3A%22com.facebook.orca%22%7D%7D&appsite_data=%7B%22android%22%3A%5B%7B%22is_app_link%22%3Afalse%2C%22app_name%22%3A%22Facebook+Messenger+for+Android%22%2C%22appsite%22%3A%22com.facebook.orca.auth.StartScreenActivity%22%2C%22fallback_url%22%3A%22https%3A%5C%2F%5C%2Fm.facebook.com%5C%2Fapps%5C%2Ffbmessenger_android%22%2C%22key_hashes%22%3A%5B%22fake_hash%22%5D%2C%22market_uri%22%3A%22market%3A%5C%2F%5C%2Fdetails%3Fid%3Dcom.facebook.orca%26referrer%3Dutm_source%5Cu00253Dapps.facebook.com%5Cu002526utm_campaign%5Cu00253Dfb4a%5Cu002526utm_content%5Cu00253D%5Cu0025257B%5Cu00252522app%5Cu00252522%5Cu0025253A256002347743983%5Cu0025252C%5Cu00252522t%5Cu00252522%5Cu0025253A1468764859%5Cu0025257D%22%2C%22package%22%3A%22com.facebook.orca%22%7D%5D%7D&has_app_link=0&accessToken=http%3A%2F%2Fwww.google.com%2F%3Fgfe_rd%3Dcr%26ei%3DjJKLV4-OEIzX8gfuvLG4Bw"

Dear facebook: For what purpose.
