### ISSUE TITLE
Workplace (Facebook at Work) support?

### ISSUE THREAD

**Issue by gil** [bitlbee/bitlbee-facebook#98]
Hi! Anyone trying to use this plugin with Workplace (Facebook at Work)? The authentication fails for me, so my guess is that the MQTT server host is different in this case, but I don't know how I can find it.

**Comment by dequis** [comment]
>but I don't know how I can find it.

If it's a matter of hosts changing (which would be ideal), wireshark should be enough. Filter by "tcp.port eq 443". Do it with both the normal app and the work app, and compare. If you can't get the traffic to go through your pc, using an emulator such as genymotion should help.

I have some notes on more advanced sniffing (such as looking inside the mqtt stream) here: https://wiki.dequis.org/notes/facebook/ - but those are mostly notes for myself, and harder to get working.

**Comment by tritnaha** [comment]
Any news on this?

**Comment by dequis** [comment]
Nope.

**Comment by dequis** [comment]
This is now implemented in https://github.com/bitlbee/bitlbee-facebook/commit/24db488909604dd389b584c1f1ce43c549648dbe
