### ISSUE TITLE
mark_read show as seen upon reply

### ISSUE THREAD

**Issue by jackusm** [bitlbee/bitlbee-facebook#99]
Combining mark_read as false and show_unread as true and reconnecting every message is relayed back. Even ones that you have 100% read as you've replied to them. It makes sense to have all messages up to a reply marked as seen.

**Comment by dequis** [comment]
`account facebook set mark_read_reply on`

**Comment by dequis** [comment]
Looks like it wasn't mentioned in https://wiki.bitlbee.org/HowtoFacebookMQTT

That is fixed now. Closing.
